name: Check by pyright and black

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: pipx install poetry
    - uses: actions/setup-python@v5
      with:
        python-version-file: 'pyproject.toml'
        cache: 'poetry'
    - run: poetry install
    - run: poetry run black --check ./
    - run: poetry run pyright
